os: linux
dist: focal
language: cpp
sudo: true
compiler:
  - gcc
addons:
  apt:
    sources:
      - sourceline: “ppa:ubuntu-toolchain-r/test”
    packages:
      - gcc-10
      - g++-10
script:
  - ./build.sh